# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.tammytang.github.io
title: Tammy Tang
email: tammytongcn@gmail.com
author: Tammy
description: "Tammy's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/tammysilva
  - icon: envelope-o
    title: email
    url: mailto:NyName@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/jiaxints/
#  - icon: file-pdf-o
#    title: CV
#    url: img/MyProject.pdf
  - icon: twitter
    title: twitter
    url: https://twitter.com/MyName

